
baseURL = 'https://cipz.github.io/'
languageCode = 'en-us'
title = "Archie"
theme="archie"
publishDir="docs"

# Code Highlight
pygmentsstyle = "monokai"

paginate=10 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/cipz/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/cvoinea/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3