
baseURL = 'https://cipz.github.io/'
languageCode = 'en-us'
title = "Archie"
theme="archie"
publishDir="docs"

# Code Highlight
pygmentsstyle = "monokai"

paginate=10 # articles per page


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/cipz/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/cvoinea/"
